server {
    listen 80;

    # API calls go to the Django service (Kubernetes Service: college-svc)
    location /students {
        proxy_pass http://college-svc:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
